[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hive-deployment"
version = "1.0.0"
description = "Remote deployment and SSH utilities for Hive applications"
authors = [
    {name = "Hive System", email = "hive@example.com"}
]
dependencies = [
    "paramiko>=3.3.0",
    "requests>=2.31.0",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pytest>=8.3.2",
    "pytest-cov>=4.1.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["hive_deployment*"]