[tool.poetry]
name = "hive-deployment"
version = "1.0.0"
description = "Remote deployment and SSH utilities for Hive applications"
authors = ["Hive System <hive@example.com>"]
packages = [{include = "hive_deployment", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
paramiko = "^3.3.0"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"