[tool.poetry]
name = "ecosystemiser"
version = "0.1.0"
description = "Climate and ecosystem analysis platform"
authors = ["Hive System <hive@example.com>"]
packages = [{include = "EcoSystemiser", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
# External dependencies
fastapi = "^0.110.0"
uvicorn = "^0.23.0"
pandas = "^2.0.0"
xarray = "^2023.1.0"
numpy = "^1.24.0"
pydantic = "^2.0.0"
pydantic-settings = "*"
httpx = "^0.25.0"
aiohttp = "^3.8.0"
click = "^8.1.0"
scipy = "^1.11.0"
python-dateutil = "^2.8.0"
pytz = "*"
timezonefinder = "^6.2.0"
structlog = "*"
tenacity = "*"
diskcache = "*"
meteostat = "*"
cdsapi = "*"
pvlib = "*"

# Hive workspace dependencies
hive-logging = {path = "../../packages/hive-logging", develop = true}
hive-config = {path = "../../packages/hive-config", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-asyncio = "*"
pytest-timeout = "*"

[tool.poetry.scripts]
ecosys = "EcoSystemiser.cli:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
pythonpath = ["src"]

[tool.black]
line-length = 120
target-version = ["py310", "py311"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true