[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ai-planner"
version = "1.0.0"
description = "Intelligent task planning and workflow generation agent for Hive system"
authors = ["Hive Team"]
readme = "README.md"
packages = [{include = "ai_planner", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.5.0"

# Hive workspace dependencies
hive-config = {path = "../../packages/hive-config", develop = true}
hive-db = {path = "../../packages/hive-db", develop = true}
hive-logging = {path = "../../packages/hive-logging", develop = true}
hive-errors = {path = "../../packages/hive-errors", develop = true}
hive-bus = {path = "../../packages/hive-bus", develop = true}
hive-orchestrator = {path = "../hive-orchestrator", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.11.1"
black = "^23.7.0"
mypy = "^1.5.0"
ruff = "^0.0.287"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "--cov=ai_planner --cov-report=html --cov-fail-under=80"

[tool.black]
line-length = 120
target-version = ['py311']

[tool.ruff]
line-length = 120
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = []
target-version = "py311"

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_any_unimported = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
check_untyped_defs = true