[tool.poetry]
name = "hive-app-toolkit"
version = "1.0.0"
description = "Production-grade application toolkit for the Hive platform - accelerating development with battle-tested patterns"
authors = ["Hive Team"]
readme = "README.md"
packages = [{include = "hive_app_toolkit", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = "^0.24.0"
pydantic = "^2.0.0"
jinja2 = "^3.1.2"
click = "^8.1.7"
pyyaml = "^6.0.1"
prometheus-client = "^0.19.0"
hive-logging = {path = "../hive-logging", develop = true}
hive-performance = {path = "../hive-performance", develop = true}
hive-cache = {path = "../hive-cache", develop = true}
hive-config = {path = "../hive-config", develop = true}
hive-errors = {path = "../hive-errors", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.23.0"
black = "^24.8.0"
mypy = "^1.8.0"
ruff = "^0.1.15"
isort = "^5.13.0"

[tool.poetry.scripts]
hive-toolkit = "hive_app_toolkit.cli.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py311']

[tool.ruff]
line-length = 120
select = ["E", "F", "I", "N", "W", "B", "C90", "UP"]

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
asyncio_mode = "auto"
