#!/usr/bin/env python3
"""
Tests for hello-service - Generated by AI Reviewer Agent
"""

import pytest
import json
import sys
import os

# Add the src directory to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from hello_service.app import app

@pytest.fixture
def client():
    """Test client fixture"""
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client

def test_hello_endpoint(client):
    """Test the main hello endpoint"""
    response = client.get('/')
    assert response.status_code == 200

    data = json.loads(response.data)
    assert data['message'] == "Hello, World!"
    assert data['service'] == "hello-service"
    assert data['version'] == "1.0.0"
    assert data['generated_by'] == "autonomous_ai_agents"

def test_health_endpoint(client):
    """Test the health check endpoint"""
    response = client.get('/health')
    assert response.status_code == 200

    data = json.loads(response.data)
    assert data['status'] == "healthy"
    assert data['service'] == "hello-service"
    assert 'uptime_seconds' in data
    assert 'endpoints' in data

def test_health_endpoints_list(client):
    """Test that health endpoint lists available endpoints"""
    response = client.get('/health')
    data = json.loads(response.data)

    assert "/" in data['endpoints']
    assert "/health" in data['endpoints']
