# hive-ui Configuration

application:
  name: hive-ui
  version: 0.1.0
  environment: development
api:
  host: 0.0.0.0
  port: 8000
  workers: 4
  enable_docs: true

logging:
  level: INFO
  format: json
  output: stdout
cache:
  enabled: true
  ttl: 3600
  max_size: 1000
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 30
