[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hivemind"
version = "1.0.0"
description = "Hive multi-agent orchestration system core"
authors = [
    {name = "Hive System", email = "hive@example.com"}
]
dependencies = [
    "hive-api",
    "hive-logging",
    "hive-db",
    "hive-deployment",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pytest>=8.3.2",
    "pytest-cov>=4.1.0",
    "flask>=3.0.0",
    "flask-cors>=4.0.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["hivemind*", "orchestrator*"]