[tool.poetry]
name = "hive-workspace"
version = "1.0.0"
description = "Hive multi-agent orchestration system workspace"
authors = ["Hive System <hive@example.com>"]
packages = []

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = "^4.1.0"
pytest-asyncio = "*"
black = "*"
isort = "*"
mypy = "*"
ruff = "^0.1.0"  # Fast Python linter - replaces many tools
flask = "^3.0.0"
flask-cors = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Define workspace members as optional dependencies for development
[tool.poetry.group.workspace]
optional = true

[tool.poetry.group.workspace.dependencies]
# Core packages
hive-logging = {path = "packages/hive-logging", develop = true}
hive-db-utils = {path = "packages/hive-db-utils", develop = true}
hive-core-db = {path = "packages/hive-core-db", develop = true}
hive-deployment = {path = "packages/hive-deployment", develop = true}
hive-config = {path = "packages/hive-config", develop = true}
hive-claude-bridge = {path = "packages/hive-claude-bridge", develop = true}
hive-errors = {path = "packages/hive-errors", develop = true}
hive-utils = {path = "packages/hive-utils", develop = true}

# Applications
ecosystemiser = {path = "apps/ecosystemiser", develop = true}
hive-orchestrator = {path = "apps/hive-orchestrator", develop = true}
ai-planner = {path = "apps/ai-planner", develop = true}
ai-reviewer = {path = "apps/ai-reviewer", develop = true}

# Ruff configuration - fast Python linter
[tool.ruff]
line-length = 120
target-version = "py311"
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "build",
    "dist",
    ".eggs",
    "*.egg",
    ".worktrees",
    "cache",
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
]
ignore = [
    "E501",  # line too long (handled by formatter)
    "B008",  # do not perform function calls in argument defaults
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"