[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hive-async"
version = "1.0.0"
description = "Async utilities and patterns for Hive platform applications"
authors = [ "Hive Platform Team <hive@example.com>",]
[[tool.poetry.packages]]
include = "hive_async"
from = "src"

[tool.poetry.dependencies]
python = "^3.11"
asyncio = "*"
aiohttp = "^3.8.0"
asyncpg = "^0.29.0"
tenacity = "^8.0.0"

[tool.pytest.ini_options]
testpaths = [ "tests",]
python_files = [ "test_*.py", "*_test.py",]
python_classes = [ "Test*",]
python_functions = [ "test_*",]
addopts = "-v --tb=short"
pythonpath = [ "src",]
asyncio_mode = "auto"

[tool.poetry.dependencies.hive-logging]
path = "../hive-logging"
develop = true

[tool.poetry.dependencies.hive-config]
path = "../hive-config"
develop = true

[tool.poetry.dependencies.hive-errors]
path = "../hive-errors"
develop = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.1.0"
mypy = "^1.8.0"
