[project]
name = "hive-test-intelligence"
version = "0.1.0"
description = "Intelligent test analysis and health monitoring for Hive platform"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.5.0",
    "rich>=13.7.0",
    "pytest>=8.3.2",
]

[project.optional-dependencies]
dev = [
    "pytest-cov>=4.1.0",
    "black>=24.8.0",
    "mypy>=1.8.0",
    "ruff>=0.1.15",
]

[project.scripts]
hive-test-intel = "hive_test_intelligence.cli:main"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["hive_test_intelligence"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
markers = [
    "core: Core infrastructure tests",
]

[tool.ruff]
line-length = 120
target-version = "py311"
select = ["E", "W", "F", "I", "B", "C4", "UP"]
ignore = ["E501"]

[tool.black]
line-length = 120
target-version = ["py311"]
