"""
Smoke tests for hive-bus package.

Auto-generated by scripts/generate_smoke_tests.py
These tests ensure all modules can be imported without errors.
"""
from __future__ import annotations

import pytest


@pytest.mark.core
def test_async_bus_imports():
    """Smoke test: async_bus module imports successfully."""
    import hive_bus.async_bus
    assert hive_bus.async_bus is not None

@pytest.mark.core
def test_base_bus_imports():
    """Smoke test: base_bus module imports successfully."""
    from hive_bus.base_bus import BaseBus
    assert BaseBus is not None

@pytest.mark.core
def test_base_events_imports():
    """Smoke test: base_events module imports successfully."""
    import hive_bus.base_events
    assert hive_bus.base_events is not None

@pytest.mark.core
def test_subscribers_imports():
    """Smoke test: subscribers module imports successfully."""
    from hive_bus.subscribers import BaseSubscriber
    assert BaseSubscriber is not None
