"""
Smoke tests for hive-cache package.

Auto-generated by scripts/generate_smoke_tests.py
These tests ensure all modules can be imported without errors.
"""

from __future__ import annotations


def test_cache_client_imports():
    """Smoke test: cache_client module imports successfully."""
    from hive_cache.cache_client import HiveCacheClient

    assert HiveCacheClient is not None


def test_claude_cache_imports():
    """Smoke test: claude_cache module imports successfully."""
    from hive_cache.claude_cache import ClaudeAPICache

    assert ClaudeAPICache is not None


def test_config_imports():
    """Smoke test: config module imports successfully."""
    from hive_cache.config import CacheConfig

    assert CacheConfig is not None


def test_exceptions_imports():
    """Smoke test: exceptions module imports successfully."""
    from hive_cache.exceptions import CacheError

    assert CacheError is not None


def test_health_imports():
    """Smoke test: health module imports successfully."""
    import hive_cache.health

    assert hive_cache.health is not None


def test_performance_cache_imports():
    """Smoke test: performance_cache module imports successfully."""
    import hive_cache.performance_cache

    assert hive_cache.performance_cache is not None
