"""
Smoke tests for hive-tests package.

Auto-generated by scripts/generate_smoke_tests.py
These tests ensure all modules can be imported without errors.
"""

from __future__ import annotations

import pytest

def test_architectural_validators_imports():
    """Smoke test: architectural_validators module imports successfully."""
    from hive_tests.architectural_validators import validate_app_contracts
    assert validate_app_contracts is not None


def test_ast_validator_imports():
    """Smoke test: ast_validator module imports successfully."""
    from hive_tests.ast_validator import Violation
    assert Violation is not None


def test_autofix_imports():
    """Smoke test: autofix module imports successfully."""
    import hive_tests.autofix
    assert hive_tests.autofix is not None


def test_autofix_enhanced_imports():
    """Smoke test: autofix_enhanced module imports successfully."""
    from hive_tests.autofix_enhanced import EnhancedAutofixResult
    assert EnhancedAutofixResult is not None


def test_enhanced_validators_imports():
    """Smoke test: enhanced_validators module imports successfully."""
    from hive_tests.enhanced_validators import CircularImportValidator
    assert CircularImportValidator is not None


def test_golden_runner_imports():
    """Smoke test: golden_runner module imports successfully."""
    from hive_tests.golden_runner import run_global_tests
    assert run_global_tests is not None


def test_test_helpers_imports():
    """Smoke test: test_helpers module imports successfully."""
    from hive_tests.test_helpers import find_hive_app_root
    assert find_hive_app_root is not None
