[tool.poetry]
name = "hive-performance"
version = "0.1.0"
description = "High-performance monitoring and metrics collection for Hive platform"
authors = ["Hive Team"]
packages = [{include = "hive_performance", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
hive-logging = {path = "../hive-logging", develop = true}
aioredis = "^2.0.1"
psutil = "^5.9.8"
prometheus-client = "^0.20.0"
structlog = "^24.1.0"
numpy = "^1.26.0"
pandas = "^2.2.0"
plotly = "^5.17.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.23.5"
pytest-mock = "^3.12.0"
black = "^24.8.0"
mypy = "^1.8.0"
ruff = "^0.1.15"
isort = "^5.13.0"

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true

[tool.ruff]
line-length = 120
target-version = "py311"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
