[tool.poetry]
name = "hive-performance"
version = "0.1.0"
description = "Performance optimization utilities for Hive platform"
authors = ["Hive Team"]

[tool.poetry.dependencies]
python = "^3.11"
hive-logging = {path = "../hive-logging", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.23.0"
black = "^24.8.0"
mypy = "^1.8.0"
ruff = "^0.1.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
