[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hive-errors"
version = "0.1.0"
description = "Generic error handling and reporting toolkit"
authors = [ "Hive System <hive@example.com>",]
[[tool.poetry.packages]]
include = "hive_errors"
from = "src"

[tool.poetry.dependencies]
python = "^3.11"

[tool.pytest.ini_options]
testpaths = [ "tests",]
python_files = [ "test_*.py", "*_test.py",]
python_classes = [ "Test*",]
python_functions = [ "test_*",]
addopts = "-v --tb=short"
pythonpath = [ "src",]
asyncio_mode = "auto"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
