[tool.poetry]
name = "hive-config"
version = "1.0.0"
description = "Secure configuration management for Hive applications"
authors = ["Hive System <hive@example.com>"]
packages = [{include = "hive_config", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"