[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hive-config"
version = "1.0.0"
description = "Secure configuration management for Hive applications"
authors = [ "Hive Platform Team <hive@example.com>",]
[[tool.poetry.packages]]
include = "hive_config"
from = "src"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.0"
cryptography = "^41.0.0"
aiofiles = "^23.2.1"
watchdog = "^3.0.0"
toml = "^0.10.2"

[tool.pytest.ini_options]
testpaths = [ "tests",]
python_files = [ "test_*.py", "*_test.py",]
python_classes = [ "Test*",]
python_functions = [ "test_*",]
addopts = "-v --tb=short"
pythonpath = [ "src",]
asyncio_mode = "auto"

[tool.poetry.dependencies.hive-logging]
path = "../hive-logging"
develop = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.1.0"
mypy = "^1.8.0"
black = "^24.8.0"
isort = "^5.13.0"
ruff = "^0.13.2"
