[app]
name = "hello-service"
version = "1.0.0"
description = "Simple test service for autonomous workflow validation"
type = "service"

[service]
port = 5000
health_endpoint = "/health"
startup_timeout = 30

[capabilities]
web_service = ["http", "json", "health-check"]
testing = ["unit-tests", "endpoint-validation"]
containerization = ["docker", "lightweight"]

[integration]
deployment_strategy = "docker"
test_framework = "pytest"
