"""Smoke tests for hive-db package.

Auto-generated by scripts/generate_smoke_tests.py
These tests ensure all modules can be imported without errors.
"""
from __future__ import annotations

import pytest


@pytest.mark.core
def test_async_pool_imports():
    """Smoke test: async_pool module imports successfully."""
    from hive_db.async_pool import create_async_sqlite_pool
    assert create_async_sqlite_pool is not None

@pytest.mark.core
def test_sqlite_factory_imports():
    """Smoke test: sqlite_factory module imports successfully."""
    from hive_db.sqlite_factory import SQLiteConnectionFactory
    assert SQLiteConnectionFactory is not None

@pytest.mark.core
def test_postgres_connector_imports():
    """Smoke test: postgres_connector module imports successfully."""
    from hive_db.postgres_connector import get_postgres_connection
    assert get_postgres_connection is not None

@pytest.mark.core
def test_sqlite_connector_imports():
    """Smoke test: sqlite_connector module imports successfully."""
    from hive_db.sqlite_connector import get_sqlite_connection
    assert get_sqlite_connection is not None

@pytest.mark.core
def test_utils_imports():
    """Smoke test: utils module imports successfully."""
    from hive_db.utils import create_table_if_not_exists
    assert create_table_if_not_exists is not None
