[tool.poetry]
name = "hive-logging"
version = "1.0.0"
description = "Structured logging utilities for Hive applications"
authors = ["Hive System <hive@example.com>"]
packages = [{include = "hive_logging", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
python-json-logger = "^2.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"