[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hive-logging"
version = "1.0.0"
description = "Structured logging utilities for Hive applications"
authors = [ "Hive System <hive@example.com>",]
[[tool.poetry.packages]]
include = "hive_logging"
from = "src"

[tool.poetry.dependencies]
python = "^3.11"
python-json-logger = "^2.0.0"

[tool.pytest.ini_options]
testpaths = [ "tests",]
python_files = [ "test_*.py", "*_test.py",]
python_classes = [ "Test*",]
python_functions = [ "test_*",]
addopts = "-v --tb=short"
pythonpath = [ "src",]
asyncio_mode = "auto"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = "^4.1.0"
