"""
Smoke tests for hive-config package.

Auto-generated by scripts/generate_smoke_tests.py
These tests ensure all modules can be imported without errors.
"""

from __future__ import annotations

import pytest

def test_async_config_imports():
    """Smoke test: async_config module imports successfully."""
    from hive_config.async_config import ConfigFileHandler
    assert ConfigFileHandler is not None


def test_loader_imports():
    """Smoke test: loader module imports successfully."""
    from hive_config.loader import load_config_for_app
    assert load_config_for_app is not None


def test_models_imports():
    """Smoke test: models module imports successfully."""
    from hive_config.models import ConfigSources
    assert ConfigSources is not None


def test_paths_imports():
    """Smoke test: paths module imports successfully."""
    from hive_config.paths import get_project_root
    assert get_project_root is not None


def test_secure_config_imports():
    """Smoke test: secure_config module imports successfully."""
    from hive_config.secure_config import SecureConfigLoader
    assert SecureConfigLoader is not None


def test_unified_config_imports():
    """Smoke test: unified_config module imports successfully."""
    from hive_config.unified_config import DatabaseConfig
    assert DatabaseConfig is not None


def test_validation_imports():
    """Smoke test: validation module imports successfully."""
    import hive_config.validation
    assert hive_config.validation is not None
