[tool.poetry]
name = "hive-tests"
version = "0.1.0"
description = "Architectural validation and testing utilities for Hive platform"
authors = ["Hive System <hive@example.com>"]
packages = [{include = "hive_tests", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.2"
toml = "*"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
black = "*"
isort = "*"
mypy = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"