[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hive-tests"
version = "0.1.0"
description = "Architectural validation and testing utilities for Hive platform"
authors = [ "Hive System <hive@example.com>",]
[[tool.poetry.packages]]
include = "hive_tests"
from = "src"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.2"
toml = "*"

[tool.pytest.ini_options]
testpaths = [ "tests",]
python_files = [ "test_*.py", "*_test.py",]
python_classes = [ "Test*",]
python_functions = [ "test_*",]
addopts = "-v --tb=short"
pythonpath = [ "src",]
asyncio_mode = "auto"

[tool.poetry.dependencies.hive-config]
path = "../hive-config"
develop = true

[tool.poetry.dependencies.hive-graph]
path = "../hive-graph"
develop = true

[tool.poetry.dependencies.hive-logging]
path = "../hive-logging"
develop = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
black = "^24.8.0"
isort = "*"
mypy = "^1.8.0"
