[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hive-tests"
version = "0.1.0"
description = "Architectural validation and testing utilities for Hive platform"
authors = [
    "Hive System <hive@example.com>",
]
packages = [
    { include = "hive_tests", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.2"
toml = "*"
pydantic = "^2.5.0"
rich = ">=13.7.0"

[tool.poetry.dependencies.hive-config]
path = "../hive-config"
develop = true

[tool.poetry.dependencies.hive-graph]
path = "../hive-graph"
develop = true

[tool.poetry.dependencies.hive-logging]
path = "../hive-logging"
develop = true

[tool.poetry.scripts]
hive-test-intel = "hive_tests.intelligence.cli:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = ">=4.1.0"
black = "^24.8.0"
isort = "*"
mypy = "^1.8.0"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
python_files = [
    "test_*.py",
    "*_test.py",
]
python_classes = [
    "Test*",
]
python_functions = [
    "test_*",
]
addopts = "-v --tb=short"
pythonpath = [
    "src",
]
asyncio_mode = "auto"
markers = [
    "core: Core infrastructure tests (packages/) - strict quality standards",
]

[tool.ruff]
line-length = 120
target-version = "py311"
exclude = [
    ".git",
    "__pycache__",
    "dist",
    "build",
    ".venv",
    "archive",
]

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "C4",
    "UP",
    "S",
]
ignore = [
    "E501",
    "B008",
    "C901",
    "COM812",
    "COM818",
    "COM819",
]

[tool.ruff.lint.isort]
known-first-party = [
    "hive_logging",
    "hive_config",
    "hive_db",
    "hive_cache",
    "hive_errors",
    "hive_bus",
    "hive_async",
    "hive_performance",
    "hive_ai",
    "hive_deployment",
    "hive_service_discovery",
    "hive_tests",
    "hive_models",
    "hive_algorithms",
    "hive_cli",
    "hive_app_toolkit",
    "hive_orchestration",
    "hive_graph",
]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
split-on-trailing-comma = false

[tool.ruff.lint.per-file-ignores]
"tests/**" = [
    "S101",
    "S602",
    "S604",
]
"scripts/**" = [
    "S602",
    "S604",
]
"archive/**" = [
    "S",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "auto"
