"""
Hive Algorithms Package

Generated by Hive Autonomous AI Agents
Contains efficient algorithm implementations for graph theory and optimization.
"""

from .dijkstra import Graph, Edge, dijkstra, find_shortest_path, DijkstraResult

__all__ = ["Graph", "Edge", "dijkstra", "find_shortest_path", "DijkstraResult"]
__version__ = "1.0.0"
