[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hive-bus"
version = "0.1.0"
description = "Generic event bus and messaging toolkit"
authors = [ "Hive Platform Team <hive@example.com>",]
[[tool.poetry.packages]]
include = "hive_bus"
from = "src"

[tool.black]
line-length = 120
target-version = [ "py38", "py39", "py310", "py311",]
include = "\\.pyi?$"
extend-exclude = "/(\n  # directories\n  \\.eggs\n  | \\.git\n  | \\.hg\n  | \\.mypy_cache\n  | \\.tox\n  | \\.venv\n  | build\n  | dist\n  | archive\n)/\n"

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true

[tool.ruff]
line-length = 120
target-version = "py38"
select = [ "E", "W", "F", "I", "B", "C4", "UP",]
ignore = [ "E501", "B008", "C901",]
exclude = [ ".git", "__pycache__", "dist", "build", ".venv", "archive",]

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
ignore_missing_imports = true
exclude = [ "archive/", "legacy/", "tests/",]

[tool.poetry.dependencies]
python = "^3.11"

[tool.pytest.ini_options]
testpaths = [ "tests",]
python_files = [ "test_*.py", "*_test.py",]
python_classes = [ "Test*",]
python_functions = [ "test_*",]
addopts = "-v --tb=short"
pythonpath = [ "src",]
asyncio_mode = "auto"

[tool.ruff.lint]
select = [ "E4", "E7", "E9", "F", "I",]

[tool.ruff.format]
quote-style = "double"

[tool.poetry.dependencies.hive-logging]
path = "../hive-logging"
develop = true

[tool.poetry.dependencies.hive-errors]
path = "../hive-errors"
develop = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.1.0"
mypy = "^1.8.0"
black = "^24.8.0"
isort = "^5.13.0"
ruff = "^0.1.15"
