[tool.poetry]
name = "hive-bus"
version = "0.1.0"
description = "Generic event bus and messaging toolkit"
authors = ["Hive System <hive@example.com>"]
packages = [{include = "hive_bus", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"