[tool.poetry]
name = "hive-core-db"
version = "1.0.0"
description = "Internal state management database for Hive orchestration system"
authors = ["Hive System <hive@example.com>"]
packages = [{include = "hive_core_db", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
hive-utils = {path = "../hive-utils", develop = true}
# No external dependencies - uses built-in sqlite3

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"