"""Smoke tests for hive-errors package.

Auto-generated by scripts/generate_smoke_tests.py
These tests ensure all modules can be imported without errors.
"""
from __future__ import annotations

import pytest


@pytest.mark.core
def test_alert_manager_imports():
    """Smoke test: alert_manager module imports successfully."""
    import hive_errors.alert_manager
    assert hive_errors.alert_manager is not None

@pytest.mark.core
def test_async_error_handler_imports():
    """Smoke test: async_error_handler module imports successfully."""
    from hive_errors.async_error_handler import ErrorContext
    assert ErrorContext is not None

@pytest.mark.core
def test_base_exceptions_imports():
    """Smoke test: base_exceptions module imports successfully."""
    from hive_errors.base_exceptions import BaseError
    assert BaseError is not None

@pytest.mark.core
def test_error_reporter_imports():
    """Smoke test: error_reporter module imports successfully."""
    from hive_errors.error_reporter import BaseErrorReporter
    assert BaseErrorReporter is not None

@pytest.mark.core
def test_monitoring_error_reporter_imports():
    """Smoke test: monitoring_error_reporter module imports successfully."""
    from hive_errors.monitoring_error_reporter import MonitoringErrorReporter
    assert MonitoringErrorReporter is not None

@pytest.mark.core
def test_predictive_alerts_imports():
    """Smoke test: predictive_alerts module imports successfully."""
    from hive_errors.predictive_alerts import AlertSeverity
    assert AlertSeverity is not None

@pytest.mark.core
def test_recovery_imports():
    """Smoke test: recovery module imports successfully."""
    from hive_errors.recovery import RecoveryStatus
    assert RecoveryStatus is not None
