[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hive-claude-bridge"
version = "1.0.0"
description = "Unified Claude CLI bridge for Hive AI system"
authors = ["Hive Team"]
readme = "README.md"
packages = [{include = "hive_claude_bridge", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.5.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.0.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]