"""
Smoke tests for hive-async package.

Auto-generated by scripts/generate_smoke_tests.py
These tests ensure all modules can be imported without errors.
"""

from __future__ import annotations

import pytest

def test_advanced_timeout_imports():
    """Smoke test: advanced_timeout module imports successfully."""
    from hive_async.advanced_timeout import TimeoutConfig
    assert TimeoutConfig is not None


def test_context_imports():
    """Smoke test: context module imports successfully."""
    from hive_async.context import AsyncResourceManager
    assert AsyncResourceManager is not None


def test_http_client_imports():
    """Smoke test: http_client module imports successfully."""
    from hive_async.http_client import ResilientHttpClient
    assert ResilientHttpClient is not None


def test_pools_imports():
    """Smoke test: pools module imports successfully."""
    from hive_async.pools import PoolConfig
    assert PoolConfig is not None


def test_resilience_imports():
    """Smoke test: resilience module imports successfully."""
    from hive_async.resilience import CircuitState
    assert CircuitState is not None


def test_retry_imports():
    """Smoke test: retry module imports successfully."""
    from hive_async.retry import AsyncRetryConfig
    assert AsyncRetryConfig is not None


def test_tasks_imports():
    """Smoke test: tasks module imports successfully."""
    import hive_async.tasks
    assert hive_async.tasks is not None
