"""
Smoke tests for hive-performance package.

Auto-generated by scripts/generate_smoke_tests.py
These tests ensure all modules can be imported without errors.
"""

from __future__ import annotations


def test_async_profiler_imports():
    """Smoke test: async_profiler module imports successfully."""
    import hive_performance.async_profiler

    assert hive_performance.async_profiler is not None


def test_metrics_collector_imports():
    """Smoke test: metrics_collector module imports successfully."""
    import hive_performance.metrics_collector

    assert hive_performance.metrics_collector is not None


def test_monitoring_service_imports():
    """Smoke test: monitoring_service module imports successfully."""
    from hive_performance.monitoring_service import MonitoringService

    assert MonitoringService is not None


def test_performance_analyzer_imports():
    """Smoke test: performance_analyzer module imports successfully."""
    import hive_performance.performance_analyzer

    assert hive_performance.performance_analyzer is not None


def test_pool_imports():
    """Smoke test: pool module imports successfully."""
    from hive_performance.pool import PoolConfig

    assert PoolConfig is not None


def test_system_monitor_imports():
    """Smoke test: system_monitor module imports successfully."""
    import hive_performance.system_monitor

    assert hive_performance.system_monitor is not None
