"""
Smoke tests for hive-app-toolkit package.

Auto-generated by scripts/generate_smoke_tests.py
These tests ensure all modules can be imported without errors.
"""

from __future__ import annotations


def test_base_app_imports():
    """Smoke test: base_app module imports successfully."""
    from hive_app_toolkit.api.base_app import HiveApp

    assert HiveApp is not None


def test_health_imports():
    """Smoke test: health module imports successfully."""
    from hive_app_toolkit.api.health import HealthStatus

    assert HealthStatus is not None


def test_main_imports():
    """Smoke test: main module imports successfully."""
    import hive_app_toolkit.cli.main

    assert hive_app_toolkit.cli.main is not None


def test_app_config_imports():
    """Smoke test: app_config module imports successfully."""
    from hive_app_toolkit.config.app_config import APIConfig

    assert APIConfig is not None


def test_cost_manager_imports():
    """Smoke test: cost_manager module imports successfully."""
    import hive_app_toolkit.cost.cost_manager

    assert hive_app_toolkit.cost.cost_manager is not None


def test_rate_limiter_imports():
    """Smoke test: rate_limiter module imports successfully."""
    from hive_app_toolkit.cost.rate_limiter import RateLimit

    assert RateLimit is not None
