[tool.poetry]
name = "hive-graph"
version = "0.1.0"
description = "Knowledge graph package for building and querying semantic representations of the Hive codebase"
authors = ["Hive Platform Team"]
readme = "README.md"
packages = [{include = "hive_graph", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.0.0"
hive-logging = {path = "../hive-logging", develop = true}
hive-models = {path = "../hive-models", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.21.0"
networkx = "^3.0"  # For in-memory graph representation during testing
mypy = "^1.8.0"
ruff = "^0.1.15"
black = "^24.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
