"""
Smoke tests for hive-models package.

Auto-generated by scripts/generate_smoke_tests.py
These tests ensure all modules can be imported without errors.
"""
import pytest

@pytest.mark.core
def test_base_imports():
    """Smoke test: base module imports successfully."""
    import hive_models.base
    assert hive_models.base is not None

@pytest.mark.core
def test_common_imports():
    """Smoke test: common module imports successfully."""
    from hive_models.common import Status
    assert Status is not None