[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hive-cache"
version = "1.0.0"
description = "High-performance Redis-based caching package for Hive platform"
authors = ["Hive Platform Engineering <engineering@hive.com>"]
readme = "README.md"
packages = [{include = "hive_cache", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
redis = {extras = ["hiredis"], version = "^5.0.0"}
pydantic = "^2.5.0"
msgpack = "^1.0.7"
orjson = "^3.9.0"
xxhash = "^3.4.1"
async-timeout = "^4.0.3"
tenacity = "^8.2.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.23.0"
pytest-cov = "^4.1.0"
black = "^24.8.0"
mypy = "^1.8.0"
ruff = "^0.1.15"
isort = "^5.13.0"
fakeredis = "^2.20.0"
