from hive_logging import get_logger

logger = get_logger(__name__)

"""
Hive Algorithms Package

Generated by Hive Autonomous AI Agents
Contains efficient algorithm implementations for graph theory and optimization.
"""

from .dijkstra import DijkstraResult, Edge, Graph, dijkstra, find_shortest_path

__all__ = ["DijkstraResult", "Edge", "Graph", "dijkstra", "find_shortest_path"]
__version__ = "1.0.0"
