# Golden Residential Microgrid - Multi-Domain Validation System
system_id: golden_residential_microgrid
timesteps: 24
description: "Multi-domain residential energy system with electrical and thermal integration for comprehensive validation"

# Profile data source
profiles:
  source: "data/profiles/golden_24h_weather_integrated.csv"
  description: "Weather-integrated electrical and thermal profiles"

# Component instances
components:
  # === ELECTRICAL DOMAIN ===

  # Grid connection
  - name: GRID
    component_id: grid_standard
    params:
      technical:
        capacity_nominal: 100.0  # 100 kW grid capacity
        import_tariff: 0.25      # €0.25/kWh import
        export_tariff: 0.10      # €0.10/kWh export
        fidelity_level: "SIMPLE"

  # Solar PV system
  - name: SOLAR_PV
    component_id: solar_pv_residential
    params:
      technical:
        capacity_nominal: 50.0   # 50 kW peak capacity (from golden dataset)
        efficiency_nominal: 1.0  # Direct profile scaling
        fidelity_level: "SIMPLE"

  # Battery storage
  - name: BATTERY
    component_id: battery_residential
    params:
      technical:
        capacity_nominal: 10.0   # 10 kWh storage
        max_charge_rate: 5.0     # 5 kW charge rate
        max_discharge_rate: 5.0  # 5 kW discharge rate
        efficiency_roundtrip: 0.95  # 95% roundtrip efficiency
        initial_soc_pct: 0.5     # Start 50% charged
        fidelity_level: "SIMPLE"

  # Power demand (base electrical load)
  - name: POWER_DEMAND
    component_id: power_demand_residential
    params:
      technical:
        capacity_nominal: 12.5   # 12.5 kW peak demand (from golden dataset)
        peak_demand: 12.5
        load_profile_type: "variable"
        fidelity_level: "SIMPLE"

  # === THERMAL DOMAIN ===

  # Heat pump (electrical to thermal conversion)
  - name: HEAT_PUMP
    component_id: heat_pump_residential
    params:
      technical:
        capacity_nominal: 15.0   # 15 kW thermal output
        electrical_capacity: 6.0 # 6 kW electrical input (at COP=2.5)
        cop_nominal: 2.5         # Nominal coefficient of performance
        min_cop: 2.0             # Minimum COP at low temperatures
        max_cop: 4.0             # Maximum COP at high temperatures
        fidelity_level: "SIMPLE"

  # Heat buffer (thermal storage)
  - name: HEAT_BUFFER
    component_id: heat_buffer_residential
    params:
      technical:
        capacity_nominal: 20.0   # 20 kWh thermal storage
        max_charge_rate: 15.0    # 15 kW thermal input
        max_discharge_rate: 15.0 # 15 kW thermal output
        thermal_efficiency: 0.95 # 95% thermal efficiency
        initial_soc_pct: 0.5     # Start 50% charged
        fidelity_level: "SIMPLE"

  # Heat demand (thermal load)
  - name: HEAT_DEMAND
    component_id: heat_demand_residential
    params:
      technical:
        capacity_nominal: 15.0   # 15 kW peak thermal demand
        peak_demand: 15.0
        load_profile_type: "variable"
        fidelity_level: "SIMPLE"

# System connections
connections:
  # === ELECTRICAL DOMAIN CONNECTIONS ===

  # Grid connections (bidirectional)
  - from: GRID
    to: POWER_DEMAND
    type: electricity
    description: "Grid supplies electrical demand"

  - from: GRID
    to: BATTERY
    type: electricity
    description: "Grid charges battery"

  - from: BATTERY
    to: GRID
    type: electricity
    description: "Battery exports to grid"

  - from: GRID
    to: HEAT_PUMP
    type: electricity
    description: "Grid powers heat pump"

  # Solar PV connections
  - from: SOLAR_PV
    to: POWER_DEMAND
    type: electricity
    description: "Solar directly supplies electrical demand"

  - from: SOLAR_PV
    to: BATTERY
    type: electricity
    description: "Solar charges battery"

  - from: SOLAR_PV
    to: GRID
    type: electricity
    description: "Solar exports to grid"

  - from: SOLAR_PV
    to: HEAT_PUMP
    type: electricity
    description: "Solar powers heat pump"

  # Battery connections
  - from: BATTERY
    to: POWER_DEMAND
    type: electricity
    description: "Battery supplies electrical demand"

  - from: BATTERY
    to: HEAT_PUMP
    type: electricity
    description: "Battery powers heat pump"

  # === THERMAL DOMAIN CONNECTIONS ===

  # Heat pump connections
  - from: HEAT_PUMP
    to: HEAT_DEMAND
    type: thermal
    description: "Heat pump directly supplies thermal demand"

  - from: HEAT_PUMP
    to: HEAT_BUFFER
    type: thermal
    description: "Heat pump charges thermal storage"

  # Heat buffer connections
  - from: HEAT_BUFFER
    to: HEAT_DEMAND
    type: thermal
    description: "Heat buffer supplies thermal demand"

# Solver configuration
solver:
  default: "rule_based"
  options:
    rule_based:
      priority_electrical: 1
      priority_thermal: 2
    milp:
      objective: "min_cost"
      solver: "CLARABEL"
      time_limit: 300

# Validation criteria
validation:
  energy_balance:
    electrical_tolerance: 1e-6  # Perfect electrical energy balance
    thermal_tolerance: 1e-6     # Perfect thermal energy balance

  physics_checks:
    battery_soc_bounds: [0.0, 1.0]      # SOC must stay in bounds
    heat_buffer_soc_bounds: [0.0, 1.0]  # Thermal SOC must stay in bounds
    flow_non_negative: true              # All flows must be non-negative

  performance_targets:
    solve_time_seconds: 5.0      # Should solve in under 5 seconds
    memory_usage_mb: 100.0       # Should use less than 100 MB

  system_behavior:
    solar_priority: true         # Solar should be used before grid
    storage_cycling: true        # Storage should charge/discharge appropriately
    thermal_coupling: true       # Heat pump should couple electrical/thermal domains
