"""
Smoke tests for hive-algorithms package.

Auto-generated by scripts/generate_smoke_tests.py
These tests ensure all modules can be imported without errors.
"""
from __future__ import annotations

import pytest


@pytest.mark.core
def test_dijkstra_imports():
    """Smoke test: dijkstra module imports successfully."""
    from hive_algorithms.dijkstra import Edge
    assert Edge is not None
