[tool.poetry]
name = "hive-api"
version = "1.0.0"
description = "API client utilities and integrations for Hive applications"
authors = ["Hive System <hive@example.com>"]
packages = [{include = "hive_api", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"