name: 📊 CI/CD Performance Audit

on:
  schedule:
    # Run monthly on the 1st at 3 AM UTC
    - cron: '0 3 1 * *'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      days_back:
        description: 'Days of history to analyze'
        required: false
        default: '30'
        type: string

permissions:
  contents: read
  actions: read
  issues: write

jobs:
  performance-audit:
    runs-on: ubuntu-latest
    name: CI/CD Performance Analysis

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run CI/CD performance analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/utils/async_resource_patterns.py \
          --repo-owner ${{ github.repository_owner }} \
          --repo-name ${{ github.event.repository.name }} \
          --days ${{ github.event.inputs.days_back || '30' }}

    - name: Create performance audit issue
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const reportContent = fs.readFileSync('ci_performance_analysis_report.md', 'utf8');

          // Look for existing performance audit issue
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['performance', 'ci-cd', 'automated'],
            state: 'open'
          });

          const issueTitle = '📊 Monthly CI/CD Performance Audit';
          const issueBody = `# CI/CD Performance Analysis Report

          This issue contains the monthly performance analysis of our CI/CD pipelines.

          ${reportContent}

          ---

          **Instructions:**
          - Review performance metrics and bottlenecks
          - Implement high-priority optimizations
          - Track cost savings from improvements
          - Close this issue when optimizations are complete

          *Generated by CI/CD Performance Audit on ${new Date().toISOString()}*`;

          if (issues.data.length > 0) {
            // Update existing issue
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issues.data[0].number,
              title: issueTitle,
              body: issueBody
            });

            // Add comment about new analysis
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issues.data[0].number,
              body: `## 📈 Monthly Performance Update - ${new Date().toLocaleDateString()}

              New performance analysis completed. Please review the updated metrics and recommendations above.`
            });
          } else {
            // Create new issue
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['performance', 'ci-cd', 'automated', 'optimization']
            });
          }

    - name: Upload performance report
      uses: actions/upload-artifact@v4
      with:
        name: ci-performance-audit-report
        path: ci_performance_analysis_report.md
        retention-days: 90
