name: 📊 Guardian Performance Metrics

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pull-requests: read

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install --with dev,workspace --no-root

      - name: Generate Weekly Report
        run: |
          poetry run python -m guardian_agent.feedback.metrics_reporter

      - name: Commit Report
        run: |
          git config user.name "Guardian AI Bot"
          git config user.email "guardian@hive-platform.ai"

          git add claudedocs/guardian_performance_weekly.md

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(guardian): Weekly performance metrics report

            Generated by Guardian AI Metrics Reporter

            🤖 Generated with [Claude Code](https://claude.com/claude-code)

            Co-Authored-By: Claude <noreply@anthropic.com>"

            git push
          fi
