name: 🔐 Regenerate Poetry Lock File

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  regenerate-lock:
    runs-on: ubuntu-latest
    # Only run this workflow if this specific file has been added/modified.
    if: "contains(github.event.head_commit.message, 'chore(ci): Regenerate poetry.lock')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need a token with write permissions to push back to the repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python and Poetry
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Regenerate lock file
        run: poetry lock

      - name: Upload generated lock file
        uses: actions/upload-artifact@v4
        with:
          name: poetry-lock
          path: poetry.lock
          retention-days: 7
